spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/urlshortener}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379